# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180404_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
