# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Type',
            field=models.CharField(max_length=255),
        ),
    ]
