# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180405_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='fuser',
            name='pw',
        ),
        migrations.RemoveField(
            model_name='fuser',
            name='yofstudy',
        ),
        migrations.AddField(
            model_name='fuser',
            name='core',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='fuser',
            name='subc',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='fid',
            field=models.IntegerField(default=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='un',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
