# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20180405_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuser',
            name='filter',
            field=models.IntegerField(default=1),
        ),
    ]
