# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_fuser_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuser',
            name='core',
        ),
        migrations.RemoveField(
            model_name='fuser',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='fuser',
            name='subc',
        ),
        migrations.AddField(
            model_name='fuser',
            name='full_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='fuser',
            name='yofstudy',
            field=models.IntegerField(null=True),
        ),
    ]
