# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20180405_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuser',
            name='post',
            field=models.CharField(default='Workforce', max_length=256),
        ),
    ]
