# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_fuser_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuser',
            name='dept',
            field=models.CharField(default='ECC', max_length=256),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='core',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='core', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='subc',
            field=models.ForeignKey(default='james', on_delete=django.db.models.deletion.CASCADE, related_name='subcore', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
