# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20180405_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='subc',
            field=models.ForeignKey(default='james', on_delete=django.db.models.deletion.CASCADE, related_name='subc', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='request',
            name='fromuser',
            field=models.ForeignKey(default='james', on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='request',
            name='touser',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='touser', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
