# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20180405_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='core',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='fuser',
            name='subc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subc', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
