# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_qcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='response',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
