# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_qcm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oversee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromd', models.CharField(max_length=256)),
                ('tod', models.CharField(max_length=256)),
                ('msg', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
            ],
        ),
    ]
