# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20180407_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='response',
            new_name='result',
        ),
    ]
