# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_request_created_at'),
        ('student', '0017_oversee'),
    ]

    operations = [
    ]
