# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_name',
            field=models.CharField(default='xxx', max_length=100),
        ),
    ]
