# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20180407_1937'),
        ('student', '0024_auto_20180407_2006'),
    ]

    operations = [
    ]
