# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_merge_20180407_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='done_at',
            field=models.DateTimeField(null=True),
        ),
    ]
