# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_callmeet_stat'),
        ('student', '0027_request_done_at'),
    ]

    operations = [
    ]
