# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 09:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0028_merge_20180408_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='brmsg',
            name='fromuser',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
