# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_merge_20180408_0208'),
        ('student', '0028_merge_20180408_0210'),
    ]

    operations = [
    ]
