# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0029_merge_20180408_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='oversee',
            name='qcms',
            field=models.ForeignKey(default='syhsnihs', on_delete=django.db.models.deletion.CASCADE, related_name='qcms', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
