# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0029_brmsg_fromuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='recent_act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('rcatid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Request', to_field='rid')),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
