# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_oversee_qcms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='attachment',
            field=models.FileField(unique=True, upload_to=student.models.upload_to),
        ),
        migrations.AlterField(
            model_name='oversee',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.FileUpload', to_field='attachment'),
        ),
    ]
