# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_auto_20180408_1009'),
        ('student', '0032_merge_20180408_1018'),
    ]

    operations = [
    ]
